name = "frreinert-api"
main = "src/index.ts"
compatibility_date = "2025-07-01"

# https://frreinert-api.fabricio-reinert.workers.dev
#
# Secrets:
#   npx wrangler secret put MERCADOPAGO_ACCESS_TOKEN
#   npx wrangler secret put MERCADOPAGO_WEBHOOK_SECRET
#   npx wrangler secret put RESEND_API_KEY

[vars]
SITE_URL = "https://frreinert.com.br"
FROM_EMAIL = "pedidos@vanguardab2b.com.br"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "frreinert-photos"

[[kv_namespaces]]
binding = "ORDERS"
id = "9d158c0d4d3844da956b396e8a4bddf7"
preview_id = "e79de38647014069a047478a66c55528"
